# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bdloko <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/06/05 17:11:08 by bdloko            #+#    #+#              #
#    Updated: 2018/06/05 17:16:13 by bdloko           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone
FILES = megaphone.cpp
FLAGS = -Wall -Werror -Wextra

all: $(NAME)

$(NAME):
	@clang++ $(FLAGS) -o $(NAME) $(FILES)

fclean:
	@rm -f $(NAME)

re: fclean
